---
title: "ERHS535_Homework5"
author: "Mollie Uhrig"
date: "2024-11-18"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

List of files in data directory:

```{r}
getwd()
list.files("../data")
```

Reading in data:

```{r}
#Reading data from Github
library(readr)

hom_url <- paste0("https://raw.githubusercontent.com/washingtonpost/data-homicides/refs/heads/master/homicide-data.csv")

homicides <- read_csv(hom_url)
```

Cleaning data:

```{r}
#Organizing the data to narrow down the dataset for relevance. 
library(tidyverse)
library(dplyr)
homicides_co <- homicides %>% 
  mutate(city_name = paste0(city, ", ", state)) %>% 
  filter(city_name == "Denver, CO") %>% 
  select("lat", "lon", "victim_race", "disposition")
```

Separating categories of homicides:

```{r}
#Categories of homicides- unsolved and solved
homicides_co_sep <- homicides_co %>% 
  mutate(status = ifelse (disposition == "Closed without arrest" | disposition == "Open/No arrest", "Unsolved", "Solved")) 
  
```

Determining three races with highest number of homicides:

```{r}
#Using fct_lump to determine races with highest number of homicides and make an "other" group. 
library(forcats)
library(dplyr)
homicides_co_sep <- homicides_co_sep%>% 
  mutate(victim_race = forcats::fct_lump(victim_race, n = 3))
```


Denver neighborhoods:

```{r}
library(tigris)
denver <- block_groups(state = c("Colorado"), county = c("Denver"), cb= TRUE, class= "sf")
```

Setting up homicides data in sf format:

```{r}
#Setting up homicides in sf format
hom_co_sf <- homicides_co_sep %>% 
  st_as_sf(coords = c("lon", "lat"), crs=4326)
```


Making the map (option 1):

```{r, fig.width=5, fig.height=8}
library(sf)
library(ggplot2)

ggplot() +
  geom_sf(data = denver) +
  geom_sf(data = hom_co_sf, aes(color= victim_race)) +
  coord_sf(datum = st_crs(4326)) +
  labs(y="Latitude", x="Longitude", color= "Victim Race")+
  ylim(39.6, 39.85)+
  xlim(105.1, 104.7)+
  ggtitle("Homicides in Denver, Colorado") +
  theme_bw()+
  facet_wrap(~ status, ncol = 1)
```

